
POST  http://localhost:3000/api/v1/book
Content-Type: application/json
Accept: application/json

{
    "title": "My fifth book title",
    "description": "My fifth book description"
}

###
GET http://localhost:3000/api/v1/book/
Content-Type: application/json
Accept: application/json

###
DELETE  http://localhost:3000/api/v1/book/10
Content-Type: application/json
Accept: application/json

###
PUT   http://localhost:3000/api/v1/book/2
Content-Type: application/json
Accept: application/json

{
    "title": "My second book title updated",
    "description": "My second book description updated"
}


###
POST  http://localhost:3000/auth/signup
Content-Type: application/json
Accept: application/json

{
    "email": "mdlo_ibb@yahoo.com",
    "password": "Maliyu1015"
}

###
GET  http://localhost:3000/auth/signout
Content-Type: application/json
Accept: application/json

###
GET  http://localhost:3000/users/dd16d85d-04a3-4f36-8c0e-517b8df66e36
Content-Type: application/json
Accept: application/json


###
POST  http://localhost:3000/products
Content-Type: application/json
Accept: application/json

{
    "title": "My Second Test",
    "description": "My Second test description!",
     "price": 99.76
}

### 
GET  http://localhost:3000/products
Content-Type: application/json
Accept: application/json

###
PATCH   http://localhost:3000/products/0.240258719238982
Content-Type: application/json
Accept: application/json

{
    "title": "My Second Updated Test"

    
}

###
DELETE   http://localhost:3000/products/0.0029576704435729795
Content-Type: application/json
Accept: application/json
    
